name: Twitchhook
version: @version@
main: com.cniekirk.twitchhook.TwitchHook
api-version: 1.16
authors: [ Charlie ]
description: Performs actions in game according to Twitch chat events
commands:
  chaos:
    description: Starts the chaos
    usage: /chaos [lowercase twitch username]
    permission: twitchhook.player
  calm:
    description: Calms the chaos
    usage: /calm
    permission: twitchhook.player
